#!/usr/bin/env bash

set -euo pipefail

if [ -z "${HOMEBREW_GITHUB_API_TOKEN:-}" ] && ! gh auth status &>/dev/null; then
    echo "GitHub token required!"
    echo "  export HOMEBREW_GITHUB_API_TOKEN=\$(gh auth token)"
    exit 1
fi
export GITHUB_TOKEN="$HOMEBREW_GITHUB_API_TOKEN"
export GH_REPO="Homebrew/homebrew-core"
command -v diffoscope >/dev/null || brew install diffoscope
command -v gum >/dev/null || brew install gum

PR=$1
COMMIT_SHA=$(gh pr view "$PR" --json=commits --jq='.commits[-1].oid')
RUN_ID=$(gh run list --commit="$COMMIT_SHA" --workflow=CI --event=pull_request --limit=1 --json=databaseId --jq='.[0].databaseId')

TEMP_DIR="$TMPDIR/pr-$PR-run-$RUN_ID-bottles"
if ! [ -d "$TEMP_DIR" ]; then
    echo "Downloading bottles to $TEMP_DIR"
    mkdir "$TEMP_DIR"
    gh run download --dir="$TEMP_DIR" --pattern='bottles_*' "$RUN_ID"
fi

RUNNERS=$(basename "$TEMP_DIR"/bottles_*/*.bottle.tar.gz | gum choose --limit=2 --output-delimiter=$'\t')
IFS=$'\t' read -r -a RUNNERS <<<"$RUNNERS"

echo "Diffing bottles in $TEMP_DIR"
diffoscope "$TEMP_DIR"/bottles_*/"${RUNNERS[0]}" "$TEMP_DIR"/bottles_*/"${RUNNERS[1]}"
