#!/usr/bin/env bash

set -euo pipefail

if [ -z "${HOMEBREW_GITHUB_API_TOKEN:-}" ] && ! gh auth status &>/dev/null; then
    echo "GitHub token required!"
    echo "  export HOMEBREW_GITHUB_API_TOKEN=\$(gh auth token)"
    exit 1
fi

formula="$1"
next="3.14" # "$(brew which-formula python3 2>/dev/null| cut -d@ -f2)"
curr="3.13" # $(echo "$next - 0.01" | bc)
branch="python@$next-$formula"
message="$formula: migrate to \`python@$next\`"
export GITHUB_TOKEN="$HOMEBREW_GITHUB_API_TOKEN"

# Check for duplicates
duplicate=$(gh pr list --search="in:title \"$message\"" --state=all --limit=1 --json=number --jq='.[].number')
if [ -n "$duplicate" ]; then
    echo "Found duplicate! https://github.com/Homebrew/homebrew-core/pull/$duplicate"
    exit 1
fi

# Update formula
git checkout main
sed -Ei "" "s/(python@?)$curr/\1$next/" Formula/*/"$formula".rb
brew update-python-resources "$formula" || true
# brew bump-revision --write-only "$formula"

# Stage and commit
git add Formula/*/"$formula".rb
git checkout --no-track -b "$branch"
git commit --no-edit -m "$message" -- Formula/*/"$formula".rb

# Create PR
git push --set-upstream fork "$branch:$branch"
gh pr create --fill --body "$message"
gh pr edit --add-label "python-$next-migration"
git checkout -q -
git branch -D "$branch"
