#!/bin/bash

set -euo pipefail

# Parse args
items=()
args=(-q)
for i in "$@"; do
    shift
    if [[ "$i" == "--" ]]; then
        args=("$@")
        break
    fi
    items+=("$i")
done

# Create PR's
for name in "${items[@]}"; do
    details=$(brew livecheck -q "$name" --json | jq -r '.[0] | select(.version.outdated==true) | to_entries')
    type=$(echo "$details" | jq -r '.[0].key')
    version=$(echo "$details" | jq -r '.[1].value.latest')
    [[ -z "$version" ]] && echo "WARNING: $name is up to date" && continue
    brew bump-"$type"-pr "$name" --version="$version" "${args[@]:-}"
done
