#!/bin/bash

set -euo pipefail

msg=$1
files=$(git diff --name-only --cached)
[ -n "$files" ] || files=$(git diff --name-only)
branch=$(basename "${files%.rb}")

if [ -z "${HOMEBREW_GITHUB_API_TOKEN:-}" ] && ! gh auth status &>/dev/null; then
    echo "GitHub token required!"
    echo "  export HOMEBREW_GITHUB_API_TOKEN=\$(gh auth token)"
    exit 1
fi

export GITHUB_TOKEN="$HOMEBREW_GITHUB_API_TOKEN" EDITOR="$HOMEBREW_EDITOR"

git checkout -b "$branch"

for file in $files; do
    formula=$(basename "${file%.rb}")
    git commit -m "$formula: $msg" -- "$file"
done

gh pr create --web
git switch -
