name: Bump

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # weekly

jobs:
  formulae:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump formulae
        uses: dawidd6/action-homebrew-bump-formula@master
        continue-on-error: true
        with:
          livecheck: true
          tap: ${{ github.repository }}
          token: ${{ secrets.GH_PAT }}
